/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from 'ethers'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'
import { TypedEventFilter, TypedEvent, TypedListener } from './commons'

interface CoFiStakingRewardsInterface extends ethers.utils.Interface {
  functions: {
    'dividendShare()': FunctionFragment
    'governance()': FunctionFragment
    'lastUpdateRewardsTokenBalance()': FunctionFragment
    'pendingSavingAmount()': FunctionFragment
    'rewardPerTokenStored()': FunctionFragment
    'rewards(address)': FunctionFragment
    'rewardsToken()': FunctionFragment
    'stakingToken()': FunctionFragment
    'userRewardPerTokenPaid(address)': FunctionFragment
    'totalSupply()': FunctionFragment
    'balanceOf(address)': FunctionFragment
    'rewardPerToken()': FunctionFragment
    'accrued()': FunctionFragment
    'earned(address)': FunctionFragment
    'stake(uint256)': FunctionFragment
    'stakeForOther(address,uint256)': FunctionFragment
    'withdraw(uint256)': FunctionFragment
    'emergencyWithdraw()': FunctionFragment
    'getReward()': FunctionFragment
    'addETHReward()': FunctionFragment
    'exit()': FunctionFragment
    'setGovernance(address)': FunctionFragment
    'setDividendShare(uint256)': FunctionFragment
    'withdrawSavingByGov(address,uint256)': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'dividendShare', values?: undefined): string
  encodeFunctionData(functionFragment: 'governance', values?: undefined): string
  encodeFunctionData(functionFragment: 'lastUpdateRewardsTokenBalance', values?: undefined): string
  encodeFunctionData(functionFragment: 'pendingSavingAmount', values?: undefined): string
  encodeFunctionData(functionFragment: 'rewardPerTokenStored', values?: undefined): string
  encodeFunctionData(functionFragment: 'rewards', values: [string]): string
  encodeFunctionData(functionFragment: 'rewardsToken', values?: undefined): string
  encodeFunctionData(functionFragment: 'stakingToken', values?: undefined): string
  encodeFunctionData(functionFragment: 'userRewardPerTokenPaid', values: [string]): string
  encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string
  encodeFunctionData(functionFragment: 'balanceOf', values: [string]): string
  encodeFunctionData(functionFragment: 'rewardPerToken', values?: undefined): string
  encodeFunctionData(functionFragment: 'accrued', values?: undefined): string
  encodeFunctionData(functionFragment: 'earned', values: [string]): string
  encodeFunctionData(functionFragment: 'stake', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'stakeForOther', values: [string, BigNumberish]): string
  encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'emergencyWithdraw', values?: undefined): string
  encodeFunctionData(functionFragment: 'getReward', values?: undefined): string
  encodeFunctionData(functionFragment: 'addETHReward', values?: undefined): string
  encodeFunctionData(functionFragment: 'exit', values?: undefined): string
  encodeFunctionData(functionFragment: 'setGovernance', values: [string]): string
  encodeFunctionData(functionFragment: 'setDividendShare', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'withdrawSavingByGov', values: [string, BigNumberish]): string

  decodeFunctionResult(functionFragment: 'dividendShare', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'governance', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'lastUpdateRewardsTokenBalance', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'pendingSavingAmount', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'rewardPerTokenStored', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'rewards', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'rewardsToken', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'stakingToken', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'userRewardPerTokenPaid', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'rewardPerToken', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'accrued', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'earned', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'stakeForOther', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'emergencyWithdraw', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getReward', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'addETHReward', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'exit', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setGovernance', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setDividendShare', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'withdrawSavingByGov', data: BytesLike): Result

  events: {
    'EmergencyWithdraw(address,uint256)': EventFragment
    'RewardAdded(address,uint256)': EventFragment
    'RewardPaid(address,uint256)': EventFragment
    'SavingWithdrawn(address,uint256)': EventFragment
    'Staked(address,uint256)': EventFragment
    'StakedForOther(address,address,uint256)': EventFragment
    'Withdrawn(address,uint256)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'EmergencyWithdraw'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RewardAdded'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RewardPaid'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'SavingWithdrawn'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Staked'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'StakedForOther'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Withdrawn'): EventFragment
}

export class CoFiStakingRewards extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this

  listeners(eventName?: string): Array<Listener>
  off(eventName: string, listener: Listener): this
  on(eventName: string, listener: Listener): this
  once(eventName: string, listener: Listener): this
  removeListener(eventName: string, listener: Listener): this
  removeAllListeners(eventName?: string): this

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>

  interface: CoFiStakingRewardsInterface

  functions: {
    dividendShare(overrides?: CallOverrides): Promise<[BigNumber]>

    governance(overrides?: CallOverrides): Promise<[string]>

    lastUpdateRewardsTokenBalance(overrides?: CallOverrides): Promise<[BigNumber]>

    pendingSavingAmount(overrides?: CallOverrides): Promise<[BigNumber]>

    rewardPerTokenStored(overrides?: CallOverrides): Promise<[BigNumber]>

    rewards(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>

    rewardsToken(overrides?: CallOverrides): Promise<[string]>

    stakingToken(overrides?: CallOverrides): Promise<[string]>

    userRewardPerTokenPaid(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>

    balanceOf(account: string, overrides?: CallOverrides): Promise<[BigNumber]>

    rewardPerToken(overrides?: CallOverrides): Promise<[BigNumber]>

    accrued(overrides?: CallOverrides): Promise<[BigNumber]>

    earned(account: string, overrides?: CallOverrides): Promise<[BigNumber]>

    stake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    stakeForOther(
      other: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    withdraw(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    emergencyWithdraw(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

    getReward(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

    addETHReward(overrides?: PayableOverrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

    exit(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

    setGovernance(
      _new: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    setDividendShare(
      share: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    withdrawSavingByGov(
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>
  }

  dividendShare(overrides?: CallOverrides): Promise<BigNumber>

  governance(overrides?: CallOverrides): Promise<string>

  lastUpdateRewardsTokenBalance(overrides?: CallOverrides): Promise<BigNumber>

  pendingSavingAmount(overrides?: CallOverrides): Promise<BigNumber>

  rewardPerTokenStored(overrides?: CallOverrides): Promise<BigNumber>

  rewards(arg0: string, overrides?: CallOverrides): Promise<BigNumber>

  rewardsToken(overrides?: CallOverrides): Promise<string>

  stakingToken(overrides?: CallOverrides): Promise<string>

  userRewardPerTokenPaid(arg0: string, overrides?: CallOverrides): Promise<BigNumber>

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>

  balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>

  rewardPerToken(overrides?: CallOverrides): Promise<BigNumber>

  accrued(overrides?: CallOverrides): Promise<BigNumber>

  earned(account: string, overrides?: CallOverrides): Promise<BigNumber>

  stake(amount: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  stakeForOther(
    other: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  withdraw(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  emergencyWithdraw(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  getReward(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  addETHReward(overrides?: PayableOverrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  exit(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  setGovernance(_new: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  setDividendShare(
    share: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  withdrawSavingByGov(
    _to: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  callStatic: {
    dividendShare(overrides?: CallOverrides): Promise<BigNumber>

    governance(overrides?: CallOverrides): Promise<string>

    lastUpdateRewardsTokenBalance(overrides?: CallOverrides): Promise<BigNumber>

    pendingSavingAmount(overrides?: CallOverrides): Promise<BigNumber>

    rewardPerTokenStored(overrides?: CallOverrides): Promise<BigNumber>

    rewards(arg0: string, overrides?: CallOverrides): Promise<BigNumber>

    rewardsToken(overrides?: CallOverrides): Promise<string>

    stakingToken(overrides?: CallOverrides): Promise<string>

    userRewardPerTokenPaid(arg0: string, overrides?: CallOverrides): Promise<BigNumber>

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>

    rewardPerToken(overrides?: CallOverrides): Promise<BigNumber>

    accrued(overrides?: CallOverrides): Promise<BigNumber>

    earned(account: string, overrides?: CallOverrides): Promise<BigNumber>

    stake(amount: BigNumberish, overrides?: CallOverrides): Promise<void>

    stakeForOther(other: string, amount: BigNumberish, overrides?: CallOverrides): Promise<void>

    withdraw(amount: BigNumberish, overrides?: CallOverrides): Promise<void>

    emergencyWithdraw(overrides?: CallOverrides): Promise<void>

    getReward(overrides?: CallOverrides): Promise<void>

    addETHReward(overrides?: CallOverrides): Promise<void>

    exit(overrides?: CallOverrides): Promise<void>

    setGovernance(_new: string, overrides?: CallOverrides): Promise<void>

    setDividendShare(share: BigNumberish, overrides?: CallOverrides): Promise<void>

    withdrawSavingByGov(_to: string, _amount: BigNumberish, overrides?: CallOverrides): Promise<void>
  }

  filters: {
    EmergencyWithdraw(
      user?: string | null,
      amount?: null
    ): TypedEventFilter<[string, BigNumber], { user: string; amount: BigNumber }>

    RewardAdded(
      sender?: null,
      reward?: null
    ): TypedEventFilter<[string, BigNumber], { sender: string; reward: BigNumber }>

    RewardPaid(
      user?: string | null,
      reward?: null
    ): TypedEventFilter<[string, BigNumber], { user: string; reward: BigNumber }>

    SavingWithdrawn(
      to?: string | null,
      amount?: null
    ): TypedEventFilter<[string, BigNumber], { to: string; amount: BigNumber }>

    Staked(
      user?: string | null,
      amount?: null
    ): TypedEventFilter<[string, BigNumber], { user: string; amount: BigNumber }>

    StakedForOther(
      user?: string | null,
      other?: string | null,
      amount?: null
    ): TypedEventFilter<[string, string, BigNumber], { user: string; other: string; amount: BigNumber }>

    Withdrawn(
      user?: string | null,
      amount?: null
    ): TypedEventFilter<[string, BigNumber], { user: string; amount: BigNumber }>
  }

  estimateGas: {
    dividendShare(overrides?: CallOverrides): Promise<BigNumber>

    governance(overrides?: CallOverrides): Promise<BigNumber>

    lastUpdateRewardsTokenBalance(overrides?: CallOverrides): Promise<BigNumber>

    pendingSavingAmount(overrides?: CallOverrides): Promise<BigNumber>

    rewardPerTokenStored(overrides?: CallOverrides): Promise<BigNumber>

    rewards(arg0: string, overrides?: CallOverrides): Promise<BigNumber>

    rewardsToken(overrides?: CallOverrides): Promise<BigNumber>

    stakingToken(overrides?: CallOverrides): Promise<BigNumber>

    userRewardPerTokenPaid(arg0: string, overrides?: CallOverrides): Promise<BigNumber>

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>

    rewardPerToken(overrides?: CallOverrides): Promise<BigNumber>

    accrued(overrides?: CallOverrides): Promise<BigNumber>

    earned(account: string, overrides?: CallOverrides): Promise<BigNumber>

    stake(amount: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    stakeForOther(
      other: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    withdraw(amount: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    emergencyWithdraw(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    getReward(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    addETHReward(overrides?: PayableOverrides & { from?: string | Promise<string> }): Promise<BigNumber>

    exit(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    setGovernance(_new: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    setDividendShare(
      share: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    withdrawSavingByGov(
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>
  }

  populateTransaction: {
    dividendShare(overrides?: CallOverrides): Promise<PopulatedTransaction>

    governance(overrides?: CallOverrides): Promise<PopulatedTransaction>

    lastUpdateRewardsTokenBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>

    pendingSavingAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>

    rewardPerTokenStored(overrides?: CallOverrides): Promise<PopulatedTransaction>

    rewards(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    rewardsToken(overrides?: CallOverrides): Promise<PopulatedTransaction>

    stakingToken(overrides?: CallOverrides): Promise<PopulatedTransaction>

    userRewardPerTokenPaid(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>

    balanceOf(account: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    rewardPerToken(overrides?: CallOverrides): Promise<PopulatedTransaction>

    accrued(overrides?: CallOverrides): Promise<PopulatedTransaction>

    earned(account: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    stake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    stakeForOther(
      other: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    withdraw(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    emergencyWithdraw(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>

    getReward(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>

    addETHReward(overrides?: PayableOverrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>

    exit(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>

    setGovernance(
      _new: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    setDividendShare(
      share: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    withdrawSavingByGov(
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>
  }
}
