/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from 'ethers'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'
import { TypedEventFilter, TypedEvent, TypedListener } from './commons'

interface ICoFiXVaultForCNodeInterface extends ethers.utils.Interface {
  functions: {
    'setGovernance(address)': FunctionFragment
    'setInitCoFiRate(uint256)': FunctionFragment
    'setDecayPeriod(uint256)': FunctionFragment
    'setDecayRate(uint256)': FunctionFragment
    'setCNodePool(address)': FunctionFragment
    'distributeReward(address,uint256)': FunctionFragment
    'getPendingRewardOfCNode()': FunctionFragment
    'currentPeriod()': FunctionFragment
    'currentCoFiRate()': FunctionFragment
    'getCoFiStakingPool()': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'setGovernance', values: [string]): string
  encodeFunctionData(functionFragment: 'setInitCoFiRate', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'setDecayPeriod', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'setDecayRate', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'setCNodePool', values: [string]): string
  encodeFunctionData(functionFragment: 'distributeReward', values: [string, BigNumberish]): string
  encodeFunctionData(functionFragment: 'getPendingRewardOfCNode', values?: undefined): string
  encodeFunctionData(functionFragment: 'currentPeriod', values?: undefined): string
  encodeFunctionData(functionFragment: 'currentCoFiRate', values?: undefined): string
  encodeFunctionData(functionFragment: 'getCoFiStakingPool', values?: undefined): string

  decodeFunctionResult(functionFragment: 'setGovernance', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setInitCoFiRate', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setDecayPeriod', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setDecayRate', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setCNodePool', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'distributeReward', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getPendingRewardOfCNode', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'currentPeriod', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'currentCoFiRate', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getCoFiStakingPool', data: BytesLike): Result

  events: {
    'NewCNodePool(address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'NewCNodePool'): EventFragment
}

export class ICoFiXVaultForCNode extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this

  listeners(eventName?: string): Array<Listener>
  off(eventName: string, listener: Listener): this
  on(eventName: string, listener: Listener): this
  once(eventName: string, listener: Listener): this
  removeListener(eventName: string, listener: Listener): this
  removeAllListeners(eventName?: string): this

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>

  interface: ICoFiXVaultForCNodeInterface

  functions: {
    setGovernance(
      _new: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    setInitCoFiRate(
      _new: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    setDecayPeriod(
      _new: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    setDecayRate(
      _new: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    setCNodePool(
      _new: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    distributeReward(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    getPendingRewardOfCNode(overrides?: CallOverrides): Promise<[BigNumber]>

    currentPeriod(overrides?: CallOverrides): Promise<[BigNumber]>

    currentCoFiRate(overrides?: CallOverrides): Promise<[BigNumber]>

    getCoFiStakingPool(overrides?: CallOverrides): Promise<[string] & { pool: string }>
  }

  setGovernance(_new: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  setInitCoFiRate(
    _new: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  setDecayPeriod(
    _new: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  setDecayRate(
    _new: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  setCNodePool(_new: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>

  distributeReward(
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  getPendingRewardOfCNode(overrides?: CallOverrides): Promise<BigNumber>

  currentPeriod(overrides?: CallOverrides): Promise<BigNumber>

  currentCoFiRate(overrides?: CallOverrides): Promise<BigNumber>

  getCoFiStakingPool(overrides?: CallOverrides): Promise<string>

  callStatic: {
    setGovernance(_new: string, overrides?: CallOverrides): Promise<void>

    setInitCoFiRate(_new: BigNumberish, overrides?: CallOverrides): Promise<void>

    setDecayPeriod(_new: BigNumberish, overrides?: CallOverrides): Promise<void>

    setDecayRate(_new: BigNumberish, overrides?: CallOverrides): Promise<void>

    setCNodePool(_new: string, overrides?: CallOverrides): Promise<void>

    distributeReward(to: string, amount: BigNumberish, overrides?: CallOverrides): Promise<void>

    getPendingRewardOfCNode(overrides?: CallOverrides): Promise<BigNumber>

    currentPeriod(overrides?: CallOverrides): Promise<BigNumber>

    currentCoFiRate(overrides?: CallOverrides): Promise<BigNumber>

    getCoFiStakingPool(overrides?: CallOverrides): Promise<string>
  }

  filters: {
    NewCNodePool(_new?: null): TypedEventFilter<[string], { _new: string }>
  }

  estimateGas: {
    setGovernance(_new: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    setInitCoFiRate(_new: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    setDecayPeriod(_new: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    setDecayRate(_new: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    setCNodePool(_new: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>

    distributeReward(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    getPendingRewardOfCNode(overrides?: CallOverrides): Promise<BigNumber>

    currentPeriod(overrides?: CallOverrides): Promise<BigNumber>

    currentCoFiRate(overrides?: CallOverrides): Promise<BigNumber>

    getCoFiStakingPool(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    setGovernance(
      _new: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    setInitCoFiRate(
      _new: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    setDecayPeriod(
      _new: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    setDecayRate(
      _new: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    setCNodePool(
      _new: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    distributeReward(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    getPendingRewardOfCNode(overrides?: CallOverrides): Promise<PopulatedTransaction>

    currentPeriod(overrides?: CallOverrides): Promise<PopulatedTransaction>

    currentCoFiRate(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getCoFiStakingPool(overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
